// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseOutputDir() {
  return window['go']['main']['App']['ChooseOutputDir']();
}

export function ChooseParentDir() {
  return window['go']['main']['App']['ChooseParentDir']();
}

export function CloneRepo(arg1, arg2) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2);
}

export function CreateFullProject(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateFullProject'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetCatalogs() {
  return window['go']['main']['App']['GetCatalogs']();
}

export function GetLastParentDir() {
  return window['go']['main']['App']['GetLastParentDir']();
}

export function GetOwners() {
  return window['go']['main']['App']['GetOwners']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplate(arg1, arg2) {
  return window['go']['main']['App']['GetTemplate'](arg1, arg2);
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function ListRepos() {
  return window['go']['main']['App']['ListRepos']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenRepo(arg1) {
  return window['go']['main']['App']['OpenRepo'](arg1);
}

export function PlanProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PlanProject'](arg1, arg2, arg3, arg4);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function PreviewProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewProject'](arg1, arg2, arg3, arg4);
}

export function PublishProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishProject'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartGitHubLogin() {
  return window['go']['main']['App']['StartGitHubLogin']();
}
