// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseOutputDir() {
  return window['go']['main']['App']['ChooseOutputDir']();
}

export function ChooseParentDir() {
  return window['go']['main']['App']['ChooseParentDir']();
}

export function CreateFullProject(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateFullProject'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetLastParentDir() {
  return window['go']['main']['App']['GetLastParentDir']();
}

export function GetOwners() {
  return window['go']['main']['App']['GetOwners']();
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PlanProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlanProject'](arg1, arg2, arg3);
}

export function PublishProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishProject'](arg1, arg2, arg3, arg4);
}

export function StartGitHubLogin() {
  return window['go']['main']['App']['StartGitHubLogin']();
}
