// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {manifest} from '../models';
import {update} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string):Promise<main.Account>;

export function AddPiece(arg1:string,arg2:string,arg3:Record<string, string>):Promise<string>;

export function ApplyUpdate():Promise<number>;

export function CheckDrift():Promise<Array<main.Drift>>;

export function CheckUpdates():Promise<main.UpdateInfo>;

export function ChooseOutputDir():Promise<string>;

export function ChooseParentDir():Promise<string>;

export function CloneRepo(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateFullProject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:string,arg9:Record<string, string>,arg10:Record<string, boolean>):Promise<main.CreatedProject>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:Record<string, boolean>):Promise<string>;

export function CreateProjectOnRemote(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Record<string, string>,arg7:Record<string, boolean>):Promise<main.CreatedProject>;

export function ExportSettings():Promise<string>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetAuthStatus():Promise<main.AuthStatus>;

export function GetCatalogs():Promise<Array<main.LoadedCatalog>>;

export function GetLastParentDir():Promise<string>;

export function GetLocalDoc(arg1:string,arg2:string):Promise<string>;

export function GetLocalOverview(arg1:string):Promise<main.LocalOverview>;

export function GetOwnerOptions():Promise<Array<main.OwnerOption>>;

export function GetOwners():Promise<Array<string>>;

export function GetRepoDoc(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetRepoOverview(arg1:string,arg2:string):Promise<main.RepoOverview>;

export function GetSettings():Promise<main.appConfig>;

export function GetTemplate(arg1:string,arg2:string):Promise<manifest.Manifest>;

export function GetVersions():Promise<main.VersionInfo>;

export function ImportSettings():Promise<main.appConfig>;

export function InstallAppUpdate():Promise<string>;

export function ListPieces(arg1:string):Promise<Array<main.PieceOption>>;

export function ListRepos():Promise<Array<main.Repo>>;

export function ListTemplateRepos():Promise<Array<string>>;

export function Logout():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenRepo(arg1:string):Promise<void>;

export function PlanProject(arg1:string,arg2:string,arg3:Record<string, string>,arg4:Record<string, boolean>):Promise<string>;

export function PreviewFile(arg1:string):Promise<string>;

export function PreviewProject(arg1:string,arg2:string,arg3:Record<string, string>,arg4:Record<string, boolean>):Promise<Array<main.PreviewEntry>>;

export function PreviewUpdate(arg1:string):Promise<update.Preview>;

export function PublishProject(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.appConfig):Promise<void>;

export function ScanProjects():Promise<Array<main.LocalProject>>;

export function StartGitHubLogin():Promise<main.AuthStatus>;

export function UpdateFileContent(arg1:string):Promise<string>;

export function GetVerifyInfo(arg1:string,arg2:string):Promise<main.VerifyInfo>;

export function StartVerify(arg1:string,arg2:string,arg3:{[key: string]: string},arg4:{[key: string]: boolean}):Promise<string>;
