// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3);
}

export function AddPiece(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPiece'](arg1, arg2, arg3);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckDrift() {
  return window['go']['main']['App']['CheckDrift']();
}

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function ChooseOutputDir() {
  return window['go']['main']['App']['ChooseOutputDir']();
}

export function ChooseParentDir() {
  return window['go']['main']['App']['ChooseParentDir']();
}

export function CloneRepo(arg1, arg2, arg3) {
  return window["go"]["main"]["App"]["CloneRepo"](arg1, arg2, arg3);
}

export function CreateFullProject(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateFullProject'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProjectOnRemote(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateProjectOnRemote'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetCatalogs() {
  return window['go']['main']['App']['GetCatalogs']();
}

export function GetLastParentDir() {
  return window['go']['main']['App']['GetLastParentDir']();
}

export function GetLocalDoc(arg1, arg2) {
  return window['go']['main']['App']['GetLocalDoc'](arg1, arg2);
}

export function GetLocalOverview(arg1) {
  return window['go']['main']['App']['GetLocalOverview'](arg1);
}

export function GetOwnerOptions() {
  return window['go']['main']['App']['GetOwnerOptions']();
}

export function GetOwners() {
  return window['go']['main']['App']['GetOwners']();
}

export function GetRepoDoc(arg1, arg2, arg3) {
  return window["go"]["main"]["App"]["GetRepoDoc"](arg1, arg2, arg3);
}

export function GetRepoOverview(arg1, arg2) {
  return window["go"]["main"]["App"]["GetRepoOverview"](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplate(arg1, arg2) {
  return window['go']['main']['App']['GetTemplate'](arg1, arg2);
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function InstallAppUpdate() {
  return window['go']['main']['App']['InstallAppUpdate']();
}

export function ListPieces(arg1) {
  return window['go']['main']['App']['ListPieces'](arg1);
}

export function ListRepos() {
  return window['go']['main']['App']['ListRepos']();
}

export function ListTemplateRepos() {
  return window['go']['main']['App']['ListTemplateRepos']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenRepo(arg1) {
  return window['go']['main']['App']['OpenRepo'](arg1);
}

export function PlanProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PlanProject'](arg1, arg2, arg3, arg4);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function PreviewProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewProject'](arg1, arg2, arg3, arg4);
}

export function PreviewUpdate(arg1) {
  return window['go']['main']['App']['PreviewUpdate'](arg1);
}

export function PublishProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishProject'](arg1, arg2, arg3, arg4);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanProjects() {
  return window['go']['main']['App']['ScanProjects']();
}

export function StartGitHubLogin() {
  return window['go']['main']['App']['StartGitHubLogin']();
}

export function UpdateFileContent(arg1) {
  return window['go']['main']['App']['UpdateFileContent'](arg1);
}
